Repository caicloud/rudder, pull requests merged in 2018-05, with the labels that each got.

#37 feat: resync release when subresources are deleted
  Makefile
  cmd/controller/app/controllers.go
  pkg/controller/release/controller.go
  pkg/release/handler.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#38 fix: avoid patching conditions if there is no change
  Makefile
  pkg/storage/release.go
  pkg/storage/release_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#39 chore(OWNERS): add li-ang to owner
  OWNERS
Labels: caicloud-cla: yes, release-note-none, size/XS

#40 fix(Makefile): fix Makefile golang build image
  Makefile.expansion
  build/controller/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#41 fix(status): fix release status
  pkg/status/assistants/apps/v1/deployment.go
Labels: approved, caicloud-cla: yes, release-note-none, size/XS
