Repository caicloud/rudder, pull requests merged in 2019-08, with the labels that each got.

#114 [CPS-3127] fix(status): delete suspend info when rollback version
  pkg/storage/release.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#115 refactor(*): unify condition functions
  pkg/release/apply.go
  pkg/release/util.go
  pkg/storage/condition.go
  pkg/storage/release.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#119 test(log): fix log print
  cmd/release-cli/lint.go
  pkg/render/render.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#113 [CPS-3018] fix(healthy): fix error phase of liveness failed
  Gopkg.lock
  cmd/controller/app/controllers.go
  cmd/controller/app/options/options.go
  cmd/controller/app/release.go
  pkg/controller/status/controller.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/types.go
  vendor/github.com/caicloud/clientset/util/status/pod_event.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#122 chore(*): use time.Duraing instead of int32
  cmd/controller/app/controllers.go
  cmd/controller/app/options/options.go
  cmd/controller/app/release.go
  pkg/controller/status/controller.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#124 chore(owner): update owners
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#127 fix(log): optimize log
  pkg/controller/gc/controller.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#129 [CPS-3429]chore(*): remove useless Jenkinsfile
  Jenkinsfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#131 fix(gc): ignore the perfrom if release.status.manifest is mepty
  pkg/controller/gc/controller.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#132 refactor(*): add comments and tweak
  pkg/controller/gc/controller.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#136 fix(gc): ignore the perfrom if release.status.manifest is mepty (#131)
  pkg/controller/gc/controller.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
